### ISSUE TITLE
git usage

### ISSUE THREAD

**Issue by s3ta** [MycroftAI/skill-weather#101]
Hi - sorry to bother you, this might be a pure git noob issue, but I'm hoping you can help me anyway ...
This skill was not working for me in german, I read the error messages, found out that there are some intent-files missing, created them, commited them and tried to push them - but the push failed like below. I thought maybe msm/mycroft does not prepare the skill to do such things maybe using an anonymous user - so I moved the folder `mycroft-weather.mycroft` ai completely to a backup place ... next try: 
I cloned this repo within my skills folder by `git clone https://s3ta@github.com/mycroftai/skill-weather`
noticed, that the directory changed from `mycroft-weather.mycroft` to `skill-weather`, restarted mycroft, found the errors (again), copied the missing intent files from my backup, restarted mycroft, skill is working again,  added and commited them and tried to push them like 
```
pi@mycroft1:~/mycroft-core/skills/skill-weather $ git push origin master
Password for 'https://s3ta@github.com': 
remote: Permission to mycroftai/skill-weather.git denied to s3ta.
fatal: unable to access 'https://s3ta@github.com/mycroftai/skill-weather/': The requested URL returned error: 403
```
 Noob thought: OK, maybe I am really not permitted to push to master - let's try branching ...
```
pi@mycroft1:~/mycroft-core/skills/skill-weather $ git checkout -b fix-lang-de-de
Zu neuem Branch 'fix-lang-de-de' gewechselt
pi@mycroft1:~/mycroft-core/skills/skill-weather $ git push origin fix-lang-de-de
Password for 'https://s3ta@github.com':
remote: Permission to mycroftai/skill-weather.git denied to s3ta.
fatal: unable to access 'https://s3ta@github.com/mycroftai/skill-weather/': The requested URL returned error: 403
```
same errors ... what am I missing? How can I contribute?

**Comment by forslund** [comment]
You don't have write permissions on the mycroft repository. Usually with git you create a "Pull request".

Common workflow is to

- create a fork (using the github ui in the top right corner)
- add your fork as a remote `git remote add mine https://github.com/YOUR-USERNAME/skill-weather/`
- create a branch `git checkout -b bugfix/german-translations`
- Do your changes and commit them
- Push to your fork `git push -u mine bugfix/german-translations
- Go to your fork on github -> branches and then click "Create Pull Request"

I see that the german translations have been done at https://translate.mycroft.ai so I'll run a pull from those and update the skill.

**Comment by s3ta** [comment]
Oic ... thanks for the detailed explanation - so I'll wait for the official update - thanks a lot
