### ISSUE TITLE
'Day' is wrong when local time offset is more than the difference in current time and UTC time

### ISSUE THREAD

**Issue by tiredoftry** [MycroftAI/skill-weather#124]
#addatest 

Given the local time offset from UTC is greater than the difference between local time and UTC time
When the users says "what is tomorrows weather"
Then "skill-weather" should reply with "tomorrow, the high will be 80 degrees"

Currently, the return text will say "today, the high will be....".   It knows the current current day, but it seems to do some conversion during the data pull and the response is using the UTC day rather than the local time day.

Example - USA Central Time has a 6 hour time offset from UTC.  Friday @ 8:00 pm Central Time is Saturday @ 2:00 am UTC time.

Asking for tomorrows weather (Saturday is tomorrow @ 8pm CST) the weather skill returns the correct weather, but states it as "Today's" weather (Saturday is today in UTC)

**Comment by krisgesling** [comment]
Thanks Randy, this is a great report and perfect candidate for a new test.

We'll need to add in some custom logic to set the device's timezone etc.

**Comment by AmateurAcademic** [comment]
Is there any update to this bug? I think I am experiencing the same issue in weather. 
Utterance: "what is the weather (like) tomorrow"
Response: today's forecast

To make sure the datetime is set correctly I used the following utterance: "what is today" and also "what time is it", I get the correct responses for both. In addition, I have tried "what is the weather (like) (tomorrow as day of the week, ie 'Wednesday')" and "what is the weather like on (month and day that is tomorrow, ie 'June 16th')", with the same response about the weather today. This doesn't seem to matter when I use these utterances (morning, noon, or nighttime). Out of curiosity I tried the utterance "what is the weather (like) this weekend", which yields the correct response. 

I'm running Mycroft in a docker container on a raspberrypi 4. The container is running the latest (main branch) version of Mycroft (21.02).

Are there any other details on what the exact problem is? Perhaps from those details a simple workaround could be determined (I'd be willing to give it a try at least).

Thank you!

**Comment by tiredoftry** [comment]
AmateurAcademic, what 'time' did you have the issue?

It happens for me when my local time (Central Time Zone USA) is a different day as compared to the UTC (6 or 7 pm till after Midnight).

Example - 6:55 pm Central Time tonight is a Tuesday in both Central and UTC.
                 7:05 pm Central Time tonight is a Tuesday in Central Time, but Wednesday UTC.

NOTE - I get the correct forecast, but the wrong 'day' is stated in the response due to the date passed being 'today' in UTC while being 'tomorrow' in the local time zone.

**Comment by AmateurAcademic** [comment]
@tiredoftry Thanks for the swift reply! As stated in my original comment: "This doesn't seem to matter when I use these utterances (morning, noon, or nighttime)".

The forecast itself is also incorrect for me (it responds with the exact same forecast as when I asked for the forecast today). So I guess this is a different issue then.

**Comment by tiredoftry** [comment]
@AmateurAcademic Sorry, missed the 'time of day didn't matter' part.  What time zone do you have set?

**Comment by AmateurAcademic** [comment]
@tiredoftry no worries! CET is the time zone, specifically 'Europe/Berlin'.

**Comment by forslund** [comment]
I think @chrisveilleux took care of this in his huge rework of the skill. You should be able to try it by asking Mycroft to "install the beta version of the weather skill"

(I haven't noticed it on my device since I did that)

**Comment by tiredoftry** [comment]
The beta seems to have fixed the issue with the wrong day being reported.  I may be having an issue with the 'right' forecast being returned. 

Tonight I asked, 'MyCroft will it rain tomorrow' (Friday) and was told 'No....'.   I then asked, 'MyCroft when will it rain next' and the response was 'There is an 82% chance of rain on Friday'.

It may be it is for a week from Friday, rather than 'tomorrow' Friday, but when I asked if it would rain on Friday, June 25th., I got an error with the weather skill.  I'll dig in more to find the error info.

**Comment by chrisveilleux** [comment]
@tiredoftry if you haven't already, please open a new bug for the incorrect forecast.  closing this one as it was fixed in the refactor

**Comment by tiredoftry** [comment]
Thanks for the information Chris.  I checked this out with the current
release and 'it' is working fine.  There is an issue with the weather skill
and the phrase "will it rain today" which I will report tonight.
