### ISSUE TITLE
Bump pyowm to latest version

### ISSUE THREAD

**Issue by domcross** [MycroftAI/skill-weather#157]
Weather skill's `requirements.txt` is currently fixed to `pyowm==2.6.1` while pyowm is now at  version 3.1. OWM introduced some interesting new features that are supported by pyowm 3.x, e.g. [One Call API](https://openweathermap.org/api/one-call-api)

~~In case there are specific reasons to stay with pyowm 2.x a version bump to 2.10-LTS should be considered.~~ According to this [timeline](https://pyowm.readthedocs.io/en/latest/v3/maintenance-streams-timelines.html) the pyowm 2.x long-term support will end 05/30/2021 (given that pyowm 3.0 was released on 05/30/2020)

**Comment by krisgesling** [comment]
Hey there, Chris is working on a big update to this Skill at the moment - including updating the pyowm API version :+1:

**Comment by emphasize** [comment]
seems requirements.txt kept untouched
```pyowm==2.6.1```

**Comment by krisgesling** [comment]
Hey @chrisveilleux was this meant to get bumped with the move to the "One Call API"?

**Comment by emphasize** [comment]
Confusingly i haven't found a bit we're using from pyowm

**Comment by chrisveilleux** [comment]
I removed pyowm from the skill, but forgot to remove the dependency.  A [PR 169](https://github.com/MycroftAI/skill-weather/pull/169) addresses this.
