### ISSUE TITLE
Use own keys

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-weather#170]
It used to be possible to use your own keys for owm, it even says so in mycroft-core readme

this functionality was broken at some point, #123 would fix this, but in #158 this functionality was completely removed

As a privacy first voice assistant, and especially being an official skill that cant be easily uninstalled and replaced without hacky blacklists, i think this functionality should be restored

at very least update the mycroft-core readme

**Comment by krisgesling** [comment]
I don't think #123 was ever functional.

Do think this should be added in again.

Also agree that we should remove that section of the readme either way since it will still be incorrect once this gets added - see PR above.
