### ISSUE TITLE
Sunrise/sunset times are incorrect in UK whilst daylight savings are active (GMT -> BST)

### ISSUE THREAD

**Issue by martini1992** [MycroftAI/skill-weather#201]
**Describe the bug**
Sunrise/sunset times are incorrect in UK whilst daylight savings are active (GMT -> BST).
The reported time seems to be in GMT, when we are currently in BST, this could hold true for other regions where daylight saving time applies.

**To Reproduce**
Steps to reproduce the behaviour:
Have the location/timezone set to Europe/London (during a time of daylight savings, summer BST, end-March to end-October), look up the sunrise/sunset time, enquire with Mycroft about the sunset/sunrise time and see that there is an hour (roughly) of difference.

**Expected behaviour**
Externally acquired sunrise/sunset times are (roughly) the same as the times reported by the skill.

**Log files**
None.

**Environment (please complete the following information):**
 - Device type: Raspberry Pi 2B
 - OS: Picroft
 - Mycroft-core version: 21.2.2

**Comment by krisgesling** [comment]
Thanks for flagging this. 

We'll need to do some more digging to work out whether this is the data we're getting back from OpenWeatherMaps, a conversion error, or something else.

**Comment by krisgesling** [comment]
Hey it was on our end.

The datetime localizer was going through a naive state which was causing issues in very specific cases. This now creates a tz aware object directly from the epoch based timestamp.
https://github.com/MycroftAI/skill-weather/commit/481e6d4a3b69a37c7273cf03ec357aa0a2d6a1df

Thanks again for reporting it :)

**Comment by martini1992** [comment]
Excellent, great work and so quick, was impressed when I woke up to find that it had all updated automatically.
