### ISSUE TITLE
Asking for the weather this/next weekend

### ISSUE THREAD

**Issue by ndarilek** [MycroftAI/skill-weather#21]
I'd like to ask questions like "What will the weather be this weekend?" and hear the forecasts for Saturday and Sunday spoken.

It looks like I can request each day individually. But when I'm making weekend plans, it makes more sense conversationally to request the weather in a batch, and to get back both forcasts at once, than it does to ask for each day individually.

Thanks!

**Comment by chrisveilleux** [comment]
This has been implemented.  Closing
