### ISSUE TITLE
Forecast does not account for timezone

### ISSUE THREAD

**Issue by tiredoftry** [MycroftAI/skill-weather#33]
I am in the US Central time zone. If it is Friday and I ask ‘MyCroft, what is the weather tomorrow’, I get the following

asking at 5:15 pm - The weather on Saturday is…
asking at 6:15 pm - The weather on Sunday is …

Looks like it is using UTC rather than the local date/time.

If I ask ‘What day is tomorrow’, MyCroft answers correctly at both times. seems to just be with the weather skill.

**Comment by pseams** [comment]
I'm having the same issue on my Mark 1. Central Standard Time.

**Comment by ScottJWalter** [comment]
System:  Picroft (mycroft-core 18.2.10)

Zone:  US Central (GMT-5 right now)
Date:  2018-07-09

When asked "what's the weather tomorrow" ,,,

... @ 12:05pm. Picroft responds "The weather on Tuesday is ..." (correct)

I'll be back in a bit, after more testing, but I'll add this now:  I also ran the `date` command from the picroft command line (ssh) and got back a date/time configured for GMT, _not_ local time.  I _know_ I set the timezone correctly when I was installing and configuring this image, so it appears that some part of the process (possibly the update process) is resetting the default timezone back to GMT?

Will dig some more.

**Comment by ScottJWalter** [comment]
Looks like this is related to #13 .

**Comment by Void-Seeker** [comment]
UTC+2, Just got funny response:

>It will not snow yesterday

When asked

>Is it going to snow?

**Comment by chrisveilleux** [comment]
These issues have been addressed in a refactor that treats timezones differently
