### ISSUE TITLE
City location is still coming out in English

### ISSUE THREAD

**Issue by JuliaC29** [MycroftAI/skill-weather#57]
Hi!
I am working on Korean, but city location is still coming out in English as below:
```
오늘 날씨가 어때요?
 >> 최고 기온은 7도, 최저 기온은 0도이며, Bloomington은 clear sky고 현재 기온은 8도입니다.
```
Does anyone have suggestions how to fix this?

**Comment by KathyReid** [comment]
I'm not sure this _can_ be fixed, because the city location is being interpreted as an English word by the STT engine. That is, this is an issue in the STT layer.

**Comment by forslund** [comment]
As Kathy is saying this is the result from the STT. One possible fix is to use the language specific normalize() function and do a translation there when the phrase is pre-processed for intent handling.

I'm closing this as it's not fixable on a skill level.
