### ISSUE TITLE
Skill-weather fails with Python error after HTTPS GET

### ISSUE THREAD

**Issue by FloatingBoater** [MycroftAI/skill-weather#7]
Original linked here:
https://community.mycroft.ai/t/skill-weather-fails-with-python-error-after-https-get/2070
Hi,

After updating my Mark 1 to mycroft-core 0.8.21 (with nightly updates), the skill-weather has stopped working.

As a greybeard former Unix sysadmin and software engineer, I have two goals here:
1. Help report and trace a bug
2. Learn and document the debug process - perhaps something to add to a FAQ?

After a look around resource, I'm unsure what the best workflow is for skill bugs, so hope someone can point me in the right direction.

Thanks!

## Issue Description
After a recent update, the weather skill has stopped working. The utterance is recognised, but Mycroft does not reply.
### Environment
1. Mycroft Mark 1
1. mycroft-core 0.8.21
1. Nightly cron job to '`apt-get update`' active
### Steps to Reproduce
1. Say 'Hey Mycroft, What's the weather?'
1. Say 'Hey Mycroft, What's the weather in Austin?'
### Expected result
1. A spoken weather forecast for my local area, as pre-configured some time ago.
1. Weather symbols on the LED matrix
### Actual Result
1. Mouth changes to listening
1. After a few seconds, the mouth goes blank (or back to the time skill clock display)
3. No speech, no response.
## Investigation
After some poking around the forums, I found how to check the Mark 1 software version, and fixed the auto-update roof cron job. I also found the main log files, and noticed errors appeared about the same time as the main skill-weather Python script timestamp. 
I know a little of GitHub from FOSS tinkering, but don't know the preferred workflow to report / diagnose skill issues.

Some basic checks:
>     pi@mark_1:~ $ apt list --installed |grep mycroft-core
>
>     WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.
>
>     mycroft-core/unknown,now 0.8.21 armhf [installed]
>     pi@mark_1:~ $ ls -la /opt/mycroft/skills/skill-weather
>     total 96
>     drwxr-xr-x  7 mycroft mycroft  4096 Aug 24 16:22 .
>     drwxrwxrwx 30 mycroft mycroft  4096 Aug 21 16:37 ..
>     drwxr-xr-x  3 mycroft mycroft  4096 May 17 01:30 dialog
>     drwxr-xr-x  8 mycroft mycroft  4096 Aug 24 16:22 .git
>     -rw-r--r--  1 mycroft mycroft 21875 Aug 21 14:04 __init__.py
>     -rw-r--r--  1 mycroft mycroft 16685 Aug 24 16:22 __init__.pyc
>     -rw-r--r--  1 mycroft mycroft  9141 Aug 21 14:04 LICENSE.md
>     -rw-r--r--  1 mycroft mycroft   125 May 17 01:30 README.md
>     drwxr-xr-x  3 mycroft mycroft  4096 May 17 01:30 regex
>     -rw-r--r--  1 mycroft mycroft    52 May 17 01:30 requirements.txt
>     -rw-r--r--  1 mycroft mycroft     2 Aug 24 16:22 settings.json
>     drwxr-xr-x  3 mycroft mycroft  4096 May 17 01:30 test
>     drwxr-xr-x  3 mycroft mycroft  4096 May 17 01:30 vocab

Mycroft logs appears to live in /var/log, and I found the test console which also reproduces the issue:
>     python -m mycroft.client.text.main --quiet
>     tail -f /var/log/mycroft-*
>     vim /var/log/mycroft-skills.log

So, tracing the skill-weather failure gives an error mesage:
>     2017-08-24 16:03:58,236 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "3c447d2c-1974-48a9-9625-c6c61f4ad80e", "utterances": ["what's the weather"]}, "context": null}
>     2017-08-24 16:03:58,280 - Skills - DEBUG - {"type": "WeatherSkill:CurrentWeatherIntent", "data": {"confidence": 0.5, "target": null, "intent_type": "WeatherSkill:CurrentWeatherIntent", "Weather": "weather", "__tags__": [{"end_token": 2, "start_token": 2, "from_context": false, "entities": [{"confidence": 1.0, "data": [["weather", "Weather"], ["Weather", "Concept"]], "key": "weather", "match": "weather"}], "key": "weather", "match": "weather"}], "utterance": "what's the weather"}, "context": {"target": null}}
>     2017-08-24 16:03:58,287 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-24 16:03:58,763 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/weather?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 451
>     2017-08-24 16:03:58,778 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-24 16:03:59,226 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 1978
>     2017-08-24 16:03:59,237 - skill-weather__init__ - ERROR - Error: 'NoneType' object has no attribute 'to_JSON'
>     2017-08-24 16:04:05,698 - Display Manager (mycroft.client.enclosure) - DEBUG - Setting active skill to TimeSkill

This suggests to me either the HTTPS call is failing, and/or the skill isn't catching the return data.
I have seen some reports of issues with web configuration of custom locations (I've used the Mycroft.ai WWW settings to setup Cramlington, England), so I also tried an explicit US location picked from other register_vocab calls in the log - Austin:
>     2017-08-24 16:51:04,747 - Skills - DEBUG - {"type": "WeatherSkill:CurrentWeatherIntent", "data": {"confidence": 0.6666666666666666, "target": null, "intent_type": "WeatherSkill:CurrentWeatherIntent", "Weather": "weather", "Location": "austin", "__tags__": [{"end_token": 2, "start_token": 2, "from_context": false, "entities": [{"confidence": 1.0, "data": [["weather", "Weather"], ["Weather", "Concept"]], "key": "weather", "match": "weather"}], "key": "weather", "match": "weather"}, {"end_token": 4, "start_token": 4, "confidence": 1.0, "from_context": false, "entities": [{"confidence": 1.0, "data": [["austin", "Location"]], "key": "austin", "match": "austin"}], "key": "austin", "match": "austin"}], "utterance": "what's the weather in austin"}, "context": {"target": null}}
>     2017-08-24 16:51:04,753 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-24 16:51:05,287 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/weather?q=austin&lang=en HTTP/1.1" 200 444
>     2017-08-24 16:51:05,302 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-24 16:51:05,763 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=austin&lang=en HTTP/1.1" 200 1989
>     2017-08-24 16:51:05,775 - skill-weather__init__ - ERROR - Error: 'NoneType' object has no attribute 'to_JSON'

So - pre-configured, or explicit locations give the same 'ERROR - Error: 'NoneType' object has no attribute 'to_JSON' in what is probably 

I don't know if the installed skill code is the latest version in GitHub, but I think the error is thrown in '/opt/mycroft/skills/skill-weather/__init__.py':
https://github.com/MycroftAI/skill-weather
https://github.com/MycroftAI/skill-weather/tree/cd782186df0cb8bb51bc803f7253a3b3a9f4caaf

My thought is to backup the skill files and then start adding LOG.info() calls into the Python code to get a feel for where the error is occurring, but don't see other text in '/var/log/mycroft-skills.log' suggesting there may be a log level setting or another file.

Any ideas please?

**Comment by forslund** [comment]
Firstly thank you for a very detailed error report.

I've seen similar issues due to the current date being out of scope for the weather service. If I'm correct that's not your problem since the location is Austin and this should only affect locations east of GMT

**Comment by FloatingBoater** [comment]
Hi @forslund ,

Thanks for replying so quickly!

After a bit more debug, the skill can be made to call both working and failing GETs with slightly different speech queries. Both OK and ERROR API requests use my configured actual location (Cramlington, England, BST=UTC+1, logs are in UTC), suggesting it's not user location but the query. I can't tell if it is server-side, or a bad client request.

The superficial difference is the working request does one GET with two forecasts returned (today 13:00, tomorrow 13:00), with the failing request doing two GETs and no return logged.
The working GET is identical to the _second_ failing GET.
>     "utterance": "will it rain today" - OK, Server returns JSON report for today and tomorrow at 13:00.
>     2017-08-25 11:13:21,994 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 1981
>    
>     "utterance": "what is the weather" - FAIL, ERROR - Error: 'NoneType' object has no attribute 'to_JSON'
>     2017-08-25 11:13:41,118 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/weather?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 454
>     2017-08-25 11:13:41,606 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 1981

I wonder if the skill is requesting a bad then a good GET, and exiting on the first error before the second (possibly) good data is returned?

And the full logs...
## "utterance": "will it rain today" - OK, Server returns JSON report for today and tomorrow at 13:00.
>     2017-08-25 11:13:19,190 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["will it rain today"]}, "context": null}
>     2017-08-25 11:13:19,288 - Skills - DEBUG - {"type": "WeatherSkill:NextPrecipitationIntent", "data": {"confidence": 1.0, "target": null, "Precipitation": "rain", "intent_type": "WeatherSkill:NextPrecipitationIntent", "Next": "will", "__tags__": [{"end_token": 0, "start_token": 0, "from_context": false, "entities": [{"confidence": 1.0, "data": [["will", "Next"]], "key": "will", "match": "will"}], "key": "will", "match": "will"}, {"end_token": 2, "start_token": 2, "from_context": false, "entities": [{"confidence": 1.0, "data": [["rain", "Precipitation"], ["rain", "WeatherType"]], "key": "rain", "match": "rain"}], "key": "rain", "match": "rain"}], "utterance": "will it rain today"}, "context": {"target": null}}
>     2017-08-25 11:13:19,291 - skill-weather__init__ - INFO - 2017-08-25 00:00:00
>     2017-08-25 11:13:19,291 - skill-weather__init__ - INFO - 2017-08-25 00:00:00
>     2017-08-25 11:13:19,299 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-25 11:13:21,994 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 1981
>     2017-08-25 11:13:22,007 - skill-weather__init__ - INFO - {"status": "Clouds", "visibility_distance": null, "clouds": 68, "temperature": {"morn": 291.35, "min": 285.99, "max": 292.72, "night": 285.99, "eve": 290.09, "day": 292.72}, "dewpoint": null, "humidex": null, "detailed_status": "broken clouds", "reference_time": 1503662400, "weather_code": 803, "sunset_time": 0, "rain": {}, "snow": {}, "pressure": {"press": 1014.41, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "04d", "humidity": 85, "wind": {"speed": 3.56}}
>     2017-08-25 11:13:22,008 - skill-weather__init__ - INFO - {"status": "Rain", "visibility_distance": null, "clouds": 12, "temperature": {"morn": 285.08, "min": 284.29, "max": 290.79, "night": 284.29, "eve": 289.45, "day": 290.52}, "dewpoint": null, "humidex": null, "detailed_status": "light rain", "reference_time": 1503748800, "weather_code": 500, "sunset_time": 0, "rain": {"all": 0.24}, "snow": {}, "pressure": {"press": 1013.4, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "humidity": 86, "wind": {"speed": 4.06}}
>     2017-08-25 11:13:22,010 - Display Manager (mycroft.client.enclosure) - DEBUG - Setting active skill to WeatherSkill
>     2017-08-25 11:13:22,014 - Skills - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "The forecast calls for light rain on Saturday"}, "context": null}

## "utterance": "what is the weather" - FAIL, ERROR - Error: 'NoneType' object has no attribute 'to_JSON'
>     2017-08-25 11:13:40,428 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["what is the weather"]}, "context": null}
>     2017-08-25 11:13:40,543 - Skills - DEBUG - {"type": "WeatherSkill:CurrentWeatherIntent", "data": {"confidence": 0.5, "target": null, "intent_type": "WeatherSkill:CurrentWeatherIntent", "Weather": "weather", "__tags__": [{"end_token": 2, "start_token": 2, "from_context": false, "entities": [{"confidence": 1.0, "data": [["weather", "Weather"], ["Weather", "Concept"]], "key": "weather", "match": "weather"}], "key": "weather", "match": "weather"}], "utterance": "what is the weather"}, "context": {"target": null}}
>     2017-08-25 11:13:40,551 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-25 11:13:41,118 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/weather?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 454
>     2017-08-25 11:13:41,138 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
>     2017-08-25 11:13:41,606 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 1981
>     2017-08-25 11:13:41,627 - skill-weather__init__ - ERROR - Error: 'NoneType' object has no attribute 'to_JSON'

**Comment by forslund** [comment]
Ok, then the issue is probably the same I saw earlier.

The current weather looks gets the date/time for the current date 2017-08-24 00:00 and is then converted to GMT Since you are at +1 this will be converted to 2017-08-*23* 23:00 and the check is then performed against the info from OWA wich doesn't provide the date in question and then None is returned.

I've was working on a fix but I had some issue with the response formating, will look at it more during Sunday. Feel free to check the code and work on the issue.

**Comment by FloatingBoater** [comment]
Hi,

Testing today now works AOK both using speech and the python console in BST = UTC+1:
```
2017-08-29 18:16:42,524 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "6a596131-b324-4a82-9442-5db90661fe76", "utterances": ["what's the weather"]}, "context": null}
2017-08-29 18:16:42,685 - Skills - DEBUG - {"type": "WeatherSkill:CurrentWeatherIntent", "data": {"confidence": 0.5, "target": null, "intent_type": "WeatherSkill:CurrentWeatherIntent", "Weather": "weather", "__tags__": [{"end_token": 2, "start_token": 2, "from_context": false, "entities": [{"confidence": 1.0, "data": [["weather", "Weather"], ["Weather", "Concept"]], "key": "weather", "match": "weather"}], "key": "weather", "match": "weather"}], "utterance": "what's the weather"}, "context": {"target": null}}
2017-08-29 18:16:42,694 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-08-29 18:16:43,303 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/weather?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 451
2017-08-29 18:16:43,333 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-08-29 18:16:43,896 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?q=Cramlington%2C+England%2C+United+Kingdom&lang=en HTTP/1.1" 200 2016
2017-08-29 18:16:43,908 - skill-weather__init__ - DEBUG - Forecast: {"status": "Clouds", "visibility_distance": null, "clouds": 92, "temperature": {"morn": 285.88, "min": 282.26, "max": 285.88, "night": 282.26, "eve": 285.07, "day": 285.88}, "dewpoint": null, "humidex": null, "detailed_status": "overcast clouds", "reference_time": 1504008000, "weather_code": 804, "sunset_time": 0, "rain": {}, "snow": {}, "pressure": {"press": 1011.87, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "04d", "humidity": 73, "wind": {"speed": 5.67}}
2017-08-29 18:16:43,910 - Display Manager (mycroft.client.enclosure) - DEBUG - Setting active skill to WeatherSkill
2017-08-29 18:16:43,914 - Skills - DEBUG - {"type": "enclosure.mouth.events.deactivate", "data": {}, "context": null}
2017-08-29 18:16:43,918 - Skills - DEBUG - {"type": "enclosure.weather.display", "data": {"temp": "13", "img_code": 1}, "context": null}
2017-08-29 18:16:43,919 - Display Manager (mycroft.client.enclosure) - DEBUG - Setting active skill to WeatherSkill
2017-08-29 18:16:43,931 - Skills - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "With a high of 13 and a low of 9, Cramlington has few clouds and is currently 13 degrees."}, "context": null}
```
The log above shows two HTTPS requests logged, and this time one response back.

As a bonus, the TTS reply gives Celsius temperatures, presumably as my account is set to Metric units (`"systemUnit": "metric"`).

Thanks for all your help!
